# Generated by Django 3.2.8 on 2021-10-21 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Adı')),
                ('location', models.CharField(max_length=1000, verbose_name='Ünvan')),
                ('phone', models.CharField(max_length=200)),
                ('facebook', models.CharField(blank=True, max_length=1000)),
                ('twitter', models.CharField(blank=True, max_length=1000)),
                ('linkedin', models.CharField(blank=True, max_length=1000)),
                ('youtube', models.CharField(blank=True, max_length=1000)),
                ('instagram', models.CharField(blank=True, max_length=1000)),
                ('status', models.CharField(choices=[('active', 'Baxılmayıb'), ('passive', 'Baxılıb')], default='passive', max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Ünvan və Telefon',
            },
        ),
        migrations.AlterModelOptions(
            name='contactusmodel',
            options={'verbose_name': 'Mesaj', 'verbose_name_plural': 'Mesajlar'},
        ),
        migrations.AlterField(
            model_name='contactusmodel',
            name='status',
            field=models.CharField(blank=True, choices=[('active', 'Baxılmayıb'), ('passive', 'Baxılıb')], default='active', max_length=20),
        ),
    ]
