# Generated by Django 3.2.8 on 2021-10-21 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20211021_2131'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='locationmodel',
            options={'verbose_name': 'Ünvan', 'verbose_name_plural': 'Ünvan və Telefonlar'},
        ),
        migrations.AddField(
            model_name='locationmodel',
            name='main',
            field=models.BooleanField(default=1, verbose_name='Əsas ünvanda göstərilsin?'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='locationmodel',
            name='phone',
            field=models.CharField(max_length=200, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='locationmodel',
            name='status',
            field=models.CharField(choices=[('active', 'Paylaşılıb'), ('passive', 'Paylaşılmayıb')], default='passive', max_length=100),
        ),
    ]
