# Generated by Django 3.2.8 on 2021-10-21 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20211021_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationmodel',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
