# Generated by Django 3.2.8 on 2021-10-21 18:11

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20211021_2206'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutus',
            options={'verbose_name': 'Haqqımızda', 'verbose_name_plural': 'Haqqımızda'},
        ),
        migrations.AddField(
            model_name='aboutus',
            name='status',
            field=models.CharField(choices=[('active', 'Paylaşılıb'), ('passive', 'Paylaşılmayıb')], default='passive', max_length=100),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='text',
            field=ckeditor.fields.RichTextField(verbose_name='Mətin'),
        ),
    ]
