# Generated by Django 3.2.8 on 2021-10-22 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20211021_2211'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Başlıq')),
                ('image', models.ImageField(upload_to='images/carousel/', verbose_name='Şəkil')),
                ('status', models.CharField(choices=[('active', 'Paylaşılıb'), ('passive', 'Paylaşılmayıb')], default='passive', max_length=100)),
                ('is_show', models.BooleanField(verbose_name='Yalnız sağda göstərilsin')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Örtük şəkili',
                'verbose_name_plural': 'Örtük şəkilləri',
            },
        ),
        migrations.AlterField(
            model_name='locationmodel',
            name='main',
            field=models.BooleanField(verbose_name='Əsas səhifədə göstərilsin?'),
        ),
    ]
