# Generated by Django 3.2.8 on 2021-10-22 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_auto_20211022_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='carousel',
            name='is_show2',
            field=models.BooleanField(default=1, verbose_name='Yalnız aşağıda göstərilsin'),
            preserve_default=False,
        ),
    ]
