# Generated by Django 3.2.9 on 2021-12-03 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0002_orderitem_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='item',
            new_name='items',
        ),
    ]
