# Generated by Django 3.2.8 on 2021-10-22 14:35

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ad')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Kateqoriya',
                'verbose_name_plural': 'Kateqoriyalar',
            },
        ),
        migrations.CreateModel(
            name='Product_Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ad')),
                ('price', models.FloatField(verbose_name='Qiymət')),
                ('stock', models.IntegerField(verbose_name='Miqdarı')),
                ('size', models.BooleanField(verbose_name='Ölçü S')),
                ('size2', models.BooleanField(verbose_name='Ölçü M')),
                ('size3', models.BooleanField(verbose_name='Ölçü L')),
                ('size4', models.BooleanField(verbose_name='Ölçü X')),
                ('size5', models.BooleanField(verbose_name='Ölçü XL')),
                ('specifcation', models.TextField(verbose_name='Tanımlama')),
                ('color', models.BooleanField(verbose_name='Rəng Qırmızı')),
                ('color2', models.BooleanField(verbose_name='Rəng Yaşıl')),
                ('color3', models.BooleanField(verbose_name='Rəng Sarı')),
                ('color4', models.BooleanField(verbose_name='Rəng Ağ')),
                ('color6', models.BooleanField(verbose_name='Rəng Göy')),
                ('color7', models.BooleanField(verbose_name='Rəng Qəhvəyi')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Məlumat')),
                ('image1', models.ImageField(upload_to='images/products/', verbose_name='Şəkil')),
                ('image2', models.ImageField(upload_to='images/products/', verbose_name='Şəkil')),
                ('image3', models.ImageField(upload_to='images/products/', verbose_name='Şəkil')),
                ('image4', models.ImageField(upload_to='images/products/', verbose_name='Şəkil')),
                ('image5', models.ImageField(blank=True, null=True, upload_to='images/products/', verbose_name='Şəkil')),
                ('status', models.CharField(choices=[('active', 'Paylaşılıb'), ('passive', 'Paylaşılmayıb')], default='passive', max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product_category')),
            ],
            options={
                'verbose_name': 'Məhsul',
                'verbose_name_plural': 'Məhsullar',
            },
        ),
    ]
