# Generated by Django 3.2.8 on 2021-10-22 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_category',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product_item',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product_category',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Şəkil'),
        ),
        migrations.AlterField(
            model_name='product_item',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Şəkil'),
        ),
    ]
