# Generated by Django 3.2.8 on 2021-10-23 07:36

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('products', '0002_auto_20211022_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_item',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='product_category',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Tarix'),
        ),
        migrations.AlterField(
            model_name='product_item',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Əlavə olunma tarixi'),
        ),
        migrations.AlterField(
            model_name='product_item',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='images/products/', verbose_name='Şəkil'),
        ),
        migrations.AlterField(
            model_name='product_item',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='images/products/', verbose_name='Şəkil'),
        ),
        migrations.AlterField(
            model_name='product_item',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='images/products/', verbose_name='Şəkil'),
        ),
    ]
